# Generated by Django 4.2.1 on 2023-09-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
