# Generated by Django 4.2.1 on 2023-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0002_alter_search_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='street_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='zip_code',
            field=models.IntegerField(blank=True),
        ),
    ]
