# Generated by Django 4.2.1 on 2023-09-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0004_alter_search_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
